---01 Activar la base de datos del sistema MASTER
USE master
GO
---02 Crear la base de datos VENTA25

CREATE DATABASE VENTA25
ON PRIMARY(
NAME=VENTA25_dat,
FILENAME='C:\DATA\VENTA25.mdf',
SIZE= 30 MB,
MAXSIZE= 50 MB,
FILEGROWTH=2 MB
)
LOG ON(
NAME=VENTA25_log,
FILENAME='C:\DATA\VENTA25.ldf',
SIZE= 10 MB,
MAXSIZE= 20 MB,
FILEGROWTH=2 MB

)
GO

---03 Activar la base de datos de usuario VENTA25

USE VENTA25
GO

---04 Crear las tablas de VENTA25

CREATE TABLE CLIENTE(
idCliente INT NOT NULL,
NOMBRE VARCHAR (50) NOT NULL,
DIRECCION VARCHAR (60) NOT NULL,
RUC CHAR (11) NOT NULL,
TELEFONO CHAR (7) NOT NULL,
WEB VARCHAR (80) NOT NULL

)


---05 Insertar filas a la tabla CLIENTE

INSERT INTO CLIENTE(idCliente,NOMBRE,DIRECCION,TELEFONO,WEB)
values (1, 'CEPSUNI','Av. Tupac Amaru 210','12345678900','4321212','www.cepsuni.edu.pe')

INSERT INTO CLIENTE(idCliente,NOMBRE,DIRECCION,TELEFONO,WEB)
values (2, 'SISTEMASUNI','Av. Tupac Amaru 210','12345678900','4321212','www.cepsuni.edu.pe')

SELECT * FROM  CLIENTE

CREATE TABLE FACTURA(

idFactura INT NOT NULL,
Fecha DATETIME NOT NULL,
Monto DECIMAL (10,2)NOT NULL,
idCliente INT NOT NULL

)

CREATE TABLE FACTURA_PRODUCTO(

idFactura INT NOT NULL REFERENCES FACTURA,
idProducto INT NOT NULL REFERENCES PRODUCTO,
Cantidad INT NOT NULL
PrecioVenta DECIMAL (6,2) NOT NULL,
PRIMARY KEY (idFactura,idProducto)
)

CREATE TABLE PRODUCTO (
idProducto INT NOT NULL,
nombre VARCHAR (40) NOT NULL,
precio DECIMAL (6,2) NOT NULL,
stock INT NOT NULL,
idCategoria INT NOT NULL

)

CREATE TABLE CATEGORIA (






