
CREATE DATABASE VENTAS
ON PRIMARY (
NAME= VENTAS_dat,
FILENAME ='C:\DATA\VENTAS.mdf',
SIZE = 30 MB,
MAXSIZE = 50 MB,
FILEGROWTH = 2MB
)LOG ON
(
NAME = VENTAS_log,
FILENAME ='C:\DATA\VENTAS.ldf',
SIZE = 10 MB,
MAXSIZE = 20 MB,
FILEGROWTH = 2MB
)
USE VENTAS
GO

CREATE TABLE DISTRITO(
COD_DIST INT NOT NULL PRIMARY KEY,
DESCRIP_DIST VARCHAR(60) NOT NULL
)

CREATE TABLE CLIENTE(
COD_CLI INT NOT NULL PRIMARY KEY,
DIRECCION_CLI VARCHAR(60) NOT NULL,
TELEFONO_CLI CHAR(10) NULL,
CODIST_CLI CHAR(10) NOT NULL,
CORREO_E_CLI VARCHAR(60) NOT NULL,
WEB VARCHAR(60)NULL,
COD_DIST INT NOT NULL REFERENCES DISTRITO
)

CREATE TABLE EMPLEADO(
COD_EMP INT NOT NULL PRIMARY KEY,
NOMBRES_EMP VARCHAR(60) NOT NULL, 
APE_PATER_EMP CHAR(60) NOT NULL,
APE_MATER_EMP CHAR(60) NOT NULL,
FECHA_NAC_EMP DATETIME NOT NULL,
DIRECCION_EMP VARCHAR(60) NOT NULL,
TELEFONO_EMP CHAR(10) NULL,
CODDIST_EMP CHAR(10) NOT NULL,
CORREO_E_EMP VARCHAR(60) NOT NULL,
FECHA_INGRESE_EMP DATETIME NOT NULL,
COD_SUPERVISOR INT NOT NULL REFERENCES EMPLEADO(COD_EMP),
COD_DIST INT NOT NULL REFERENCES DISTRITO
)

CREATE TABLE CLIENTE_NATURAL(
COD_CLI INT NOT NULL REFERENCES CLIENTE,
NOMBRE_CLI CHAR(60) NOT NULL,
APE_PATER_CLI CHAR(60) NOT NULL,
APE_MATER_CLI CHAR(60) NOT NULL,
PRIMARY KEY (COD_CLI)
)

CREATE TABLE CLIENTE_JURIDICO(
COD_CLI INT NOT NULL REFERENCES CLIENTE,
RAZONZOCIAL_CLI VARCHAR(60) NOT NULL,
RUC_CLI CHAR(10) NOT NULL,
CONTACTO_CLI VARCHAR(60) NOT NULL,
COD_CARGO_CLI CHAR(10) NOT NULL,
PRIMARY KEY (COD_CLI)
)

CREATE TABLE DETALLE_BOLETA(
COD_BOL INT NOT NULL REFERENCES BOLETA,
COD_PRO INT NOT NULL,
CANTIDAD INT NOT NULL,
PRECIOVENTA DECIMAL(8,2) NOT NULL,
PRIMARY KEY (COD_BOL)
)

ALTER TABLE DETALLE_BOLETA
ADD CONSTRAINT fk_producto
FOREIGN KEY (COD_PRO)
REFERENCES PRODUCTO (COD_PRO)

DROP TABLE DETALLE_BOLETA

CREATE TABLE DETALLE_BOLETA(
COD_BOL INT NOT NULL REFERENCES BOLETA,
COD_PRO INT NOT NULL REFERENCES PRODUCTO,
CANTIDAD INT NOT NULL,
PRECIOVENTA DECIMAL(8,2) NOT NULL,
PRIMARY KEY (COD_BOL)
)

DROP TABLE DETALLE_BOLETA

CREATE TABLE DETALLE_BOLETA(
COD_BOL INT NOT NULL REFERENCES BOLETA,
COD_PRO INT NOT NULL REFERENCES PRODUCTO,
CANTIDAD INT NOT NULL,
PRECIOVENTA DECIMAL(8,2) NOT NULL,
PRIMARY KEY (COD_BOL,COD_PRO)
)

CREATE TABLE BOLETA(
COD_BOL INT NOT NULL PRIMARY KEY,
COD_EMP INT NOT NULL REFERENCES EMPLEADO,
FECHA_BOL DATETIME NOT NULL,
COD_CLI INT NOT NULL REFERENCES CLIENTE,
ESTADO_BOL VARCHAR(10) NOT NULL
)

CREATE TABLE PRODUCTO(
COD_PRO INT NOT NULL PRIMARY KEY,
DESCRIP_PRO VARCHAR(60) NOT NULL,
PRECIO_PRO DECIMAL(8,2) NOT NULL,
STOCK_ACT_PRO INT NOT NULL,
STOCK_MIN_PRO INT NOT NULL,
COD_TIPO_PRO CHAR(10) NOT NULL REFERENCES TIPO_PRODUCTO
)

CREATE TABLE TIPO_PRODUCTO(
COD_TIPO_PRO CHAR(10) NOT NULL PRIMARY KEY,
DESCRIP_TIPO_PRO VARCHAR(60) NOT NULL
)

--------------------------------------------

ALTER TABLE CLIENTE
ADD CONSTRAINT DF_CORREO_E_CLI DEFAULT 'NO REGISTRA'
FOR CORREO_E_CLI

ALTER TABLE PRODUCTO
ADD CONSTRAINT chk_precio_pro
CHECK (PRECIO_PRO >= 0 AND PRECIO_PRO <= 0) 

ALTER TABLE EMPLEADO
ADD CONSTRAINT chk_fecha_nac_emp
CHECK (FECHA_NAC_EMP < GETDATE ()) 

ALTER TABLE PRODUCTO
ADD CONSTRAINT DF_COD_TIPO_PRO DEFAULT 'TIPO_01'
FOR COD_TIPO_PRO

CREATE TABLE CLIENTE_BAK(
COD_CLI INT NOT NULL PRIMARY KEY,
DIRECCION_CLI VARCHAR(60) NOT NULL,
TELEFONO_CLI CHAR(10) NULL,
CODIST_CLI CHAR(10) NOT NULL,
CORREO_E_CLI VARCHAR(60) NOT NULL,
WEB VARCHAR(60)NULL,
COD_DIST INT NOT NULL REFERENCES DISTRITO
)

DROP TABLE CLIENTE_BAK

CREATE TABLE CLIENTE_BAK(
COD_CLI INT NOT NULL IDENTITY,
DIRECCION_CLI VARCHAR(60) NOT NULL,
TELEFONO_CLI CHAR(10) NULL,
CODIST_CLI CHAR(10) NOT NULL,
CORREO_E_CLI VARCHAR(60) NOT NULL,
WEB VARCHAR(60)NULL,
COD_DIST INT NOT NULL REFERENCES DISTRITO
)

INSERT INTO CLIENTE_BAK(DIRECCION_CLI,TELEFONO_CLI,CODIST_CLI,CORREO_E_CLI,WEB,COD_DIST)
VALUES('Av. Grau','5323834',11,'abc@hotmail.com','www.abc.com',1)

INSERT INTO CLIENTE_BAK(DIRECCION_CLI,TELEFONO_CLI,CODIST_CLI,CORREO_E_CLI,WEB,COD_DIST)
VALUES('Av. Pershing','2781056',22,'def@hotmail.com','www.def.com',2)

INSERT INTO CLIENTE_BAK(DIRECCION_CLI,TELEFONO_CLI,CODIST_CLI,CORREO_E_CLI,WEB,COD_DIST)
VALUES('Av. Wilson','4492984',33,'ghi@hotmail.com','www.ghi.com',3)

SELECT * FROM CLIENTE_BAK

SELECT * FROM DISTRITO

INSERT INTO DISTRITO(COD_DIST,DESCRIP_DIST)
VALUES(1,'CERCADO')

INSERT INTO DISTRITO(COD_DIST,DESCRIP_DIST)
VALUES(2,'SAN_MIGUEL')

INSERT INTO DISTRITO(COD_DIST,DESCRIP_DIST)
VALUES(3,'SURCO')

