Create DATABASE MarketPeru

ON PRIMARY (
NAME=MarketPeru_dat,
FILENAME='C:\DATA\MarketPeru.mdf',
SIZE=30 MB,
MAXSIZE=50 MB,
FILEGROWTH = 2 MB
)
LOG ON (
NAME=MarketPeru_log,
FILENAME='C:\DATA\MarketPeru.ldf',
SIZE=10 MB,
MAXSIZE=20 MB,
FILEGROWTH = 2 MB
)
go

use MarketPeru
go

CREATE TABLE ORDEN(
idOrden INT NOT NULL,
FechaOrden  DATETIME NOT NULL,
FechaEntrada DATETIME NOT NULL
)

ALTER TABLE ORDEN 
ADD CONSTRAINT pk_orden
PRIMARY KEY (idOrden)

CREATE TABLE PROVEEDOR(
idProveedor INT NOT NULL,
Nombre VARCHAR(60)NOT NULL,
Representante VARCHAR(60)NOT NULL,
Direcciòn VARCHAR(60)NOT NULL,
Ciudad VARCHAR(20) NOT NULL,
Departamento VARCHAR(20)NOT NULL,
CodigoPostal VARCHAR(10)NOT NULL,
Telefono VARCHAR(10)NOT NULL,
Fax VARCHAR(20)NOT NULL
)

ALTER TABLE PROVEEDOR 
ADD CONSTRAINT pk_proveedor
PRIMARY KEY (idProveedor)

CREATE TABLE CATEGORIA(
idCategoria INT NOT NULL,
Categoria VARCHAR (20) NOT NULL,
Descripcion VARCHAR (30) NOT NULL
)

ALTER TABLE CATEGORIA 
ADD CONSTRAINT pk_categoria
PRIMARY KEY (idCategoria)

CREATE TABLE ORDEN_DETALLE(
idOrden INT NOT NULL,
idProducto INT NOT NULL,
PrecioCompra DECIMAL(8,2)NOT NULL,
CantidadSolicitada INT NOT NULL,
CantidadRecibida INT NOT NULL,
Estado VARCHAR(20)NOT NULL
)

ALTER TABLE ORDEN_DETALLE 
ADD CONSTRAINT pk_orden_producto
PRIMARY KEY (idOrden,idProducto)

ALTER TABLE ORDEN_DETALLE 
DROP CONSTRAINT pk_orden_producto

ALTER TABLE ORDEN_DETALLE 
ADD CONSTRAINT fk_Orden
FOREIGN KEY (idOrden)
REFERENCES ORDEN (idOrden)

DROP TABLE ORDEN_DETALLE

CREATE TABLE ORDEN_DETALLE(
idOrden INT NOT NULL REFERENCES ORDEN,
idProducto INT NOT NULL REFERENCES PRODUCTO,
PrecioCompra DECIMAL(8,2)NOT NULL,
CantidadSolicitada INT NOT NULL,
CantidadRecibida INT NOT NULL,
Estado VARCHAR(20)NOT NULL,
PRIMARY KEY (idOrden,idProducto)
)

CREATE TABLE PRODUCTO(
idProducto INT NOT NULL,
idCategoria INT NOT NULL,
idProveedor INT NOT NULL,
Nombre VARCHAR(60)NOT NULL,
UnidadMedida VARCHAR(20) NOT NULL,
PrecioProveedor DECIMAL (8,2)NOT NULL,
StockActual INT NOT NULL,
StockMinimo INT NOT NULL,
Descontinuado VARCHAR (20)NOT NULL
)


ALTER TABLE PRODUCTO
ADD CONSTRAINT pk_producto
PRIMARY KEY (idProducto)

ALTER TABLE PRODUCTO
ADD CONSTRAINT fk_Categoria
FOREIGN KEY (idCategoria)
REFERENCES CATEGORIA (idCategoria)

ALTER TABLE PRODUCTO
ADD CONSTRAINT fk_proveedor
FOREIGN KEY (idProveedor)
REFERENCES PROVEEDOR (idProveedor)


CREATE TABLE GUIA_DETALLE(
idGuia INT NOT NULL,
idProducto INT NOT NULL,
PrecioVenta DECIMAL(8,2)NOT NULL,
Cantidad INT NOT NULL
)

ALTER TABLE GUIA_DETALLE
ADD CONSTRAINT pk_guia
PRIMARY KEY (idGuia)

ALTER TABLE GUIA_DETALLE
ADD CONSTRAINT fk_guia
FOREIGN KEY (idGuia)
REFERENCES GUIA (idGuia)

ALTER TABLE GUIA_DETALLE
ADD CONSTRAINT fk_producto
FOREIGN KEY (idProducto)
REFERENCES PRODUCTO (idProducto)

drop table GUIA_DETALLE

CREATE TABLE GUIA_DETALLE(
idGuia INT NOT NULL REFERENCES GUIA,
idProducto INT NOT NULL REFERENCES PRODUCTO,
PrecioVenta DECIMAL(8,2)NOT NULL,
Cantidad INT NOT NULL
PRIMARY KEY (idGuia)
)

drop table GUIA_DETALLE

CREATE TABLE GUIA_DETALLE(
idGuia INT NOT NULL REFERENCES GUIA,
idProducto INT NOT NULL REFERENCES PRODUCTO,
PrecioVenta DECIMAL(8,2)NOT NULL,
Cantidad INT NOT NULL
PRIMARY KEY (idGuia,idProducto)
)

CREATE TABLE GUIA(
idGuia INT NOT NULL,
idLocal INT NOT NULL,
FechaSalida DATETIME NOT NULL,
Transportista VARCHAR(60) NOT NULL
)

ALTER TABLE GUIA
ADD CONSTRAINT fk_guia
FOREIGN KEY (idGuia)
REFERENCES GUIA_DETALLE(idGuia)

ALTER TABLE GUIA
DROP CONSTRAINT fk_guia

ALTER TABLE GUIA
ADD CONSTRAINT pk_guia
PRIMARY KEY (idGuia)

ALTER TABLE GUIA
ADD CONSTRAINT fk_local
FOREIGN KEY (idLocal)
REFERENCES LOCAL (idLocal)


CREATE TABLE LOCAL(
idLocal INT NOT NULL,
Direcciòn VARCHAR(60)NOT NULL,
Distrito VARCHAR(60)NOT NULL,
Telefono VARCHAR(10)NOT NULL,
Fax VARCHAR(20)NOT NULL


ALTER TABLE LOCAL
ADD CONSTRAINT pk_local
PRIMARY KEY (idLocal)

)
