

Create DATABASE MarketPeru
go

use MarketPeru
go

CREATE TABLE ORDEN(
idOrden INT NOT NULL,
FechaOrden  DATETIME NOT NULL,
FechaEntrada DATETIME NOT NULL
)

CREATE TABLE PROVEEDOR(
idProveedor INT NOT NULL,
Nombre VARCHAR(60)NOT NULL,
Representante VARCHAR(60)NOT NULL,
Direcciòn VARCHAR(60)NOT NULL,
Ciudad VARCHAR(20) NOT NULL,
Departamento VARCHAR(20)NOT NULL,
CodigoPostal VARCHAR(10)NOT NULL,
Telefono VARCHAR(10)NOT NULL,
Fax VARCHAR(20)NOT NULL
)

CREATE TABLE CATEGORIA(
idCategoria INT NOT NULL,
Categoria VARCHAR (20) NOT NULL,
Descripcion VARCHAR (30) NOT NULL
)

CREATE TABLE ORDEN_DETALLE(
idOrden INT NOT NULL,
idProducto INT NOT NULL,
PrecioCompra DECIMAL(8,2)NOT NULL,
CantidadSolicitada INT NOT NULL,
CantidadRecibida INT NOT NULL,
Estado VARCHAR(20)NOT NULL
)

CREATE TABLE PRODUCTO(
idProducto INT NOT NULL,
idCategoria INT NOT NULL,
idProveedor INT NOT NULL,
Nombre VARCHAR(60)NOT NULL,
UnidadMedida VARCHAR(20) NOT NULL,
PrecioProveedor DECIMAL (8,2)NOT NULL,
StockActual INT NOT NULL,
StockMinimo INT NOT NULL,
Descontinuado VARCHAR (20)NOT NULL
)


CREATE TABLE GUIA_DETALLE(
idGuia INT NOT NULL,
idProducto INT NOT NULL,
PrecioVenta DECIMAL(8,2)NOT NULL,
Cantidad INT NOT NULL
)


CREATE TABLE GUIA(
idGuia INT NOT NULL,
idLocal INT NOT NULL,
FechaSalida DATETIME NOT NULL,
Transportista VARCHAR(60) NOT NULL
)

CREATE TABLE LOCAL(
idLocal INT NOT NULL,
Direcciòn VARCHAR(60)NOT NULL,
Distrito VARCHAR(60)NOT NULL,
Telefono VARCHAR(10)NOT NULL,
Fax VARCHAR(20)NOT NULL
)
