
Create DATABASE Ventas
go

use Ventas
go

CREATE TABLE Distrito(
COD_DIST VARCHAR (10) NOT NULL,
DESCRIP_DIST  VARCHAR (30) NOT NULL,

)

CREATE TABLE CLIENTE_JURIDICO(
COD_CLI VARCHAR(10)NOT NULL,
RAZON_SOCIAL_CLI VARCHAR(50)NOT NULL,
RUC_CLI VARCHAR(20)NOT NULL,
CONTACTO_CLI VARCHAR(50) NOT NULL,
COD_CARGO_CLI VARCHAR(10)NOT NULL,

)

CREATE TABLE EMPLEADO(
COD_EMP VARCHAR (10) NOT NULL,
NOMBRES_EMP VARCHAR (20) NOT NULL,
APE_PATER_EMP VARCHAR (30) NOT NULL,
APE_MATER_EMP VARCHAR (30) NOT NULL,
FECHA_NAC_EMP DATETIME NOT NULL,
DIRECCION_EMP VARCHAR(50)NOT NULL,
TELEFONO_EMP VARCHAR (10) NOT NULL,
CODDIST_EMP VARCHAR (10) NOT NULL,
CORREO_E_EMP VARCHAR (25) NOT NULL,
FECHA_INGRESO_EMP DATETIME NOT NULL,
COD_SUPERVISOR VARCHAR (10) NOT NULL

)

CREATE TABLE CLIENTE(
COD_CLI VARCHAR (10) NOT NULL,
DIRECCION_CLI VARCHAR(50)NOT NULL,
TELEFONO_CLI VARCHAR (10) NOT NULL,
CODDIST_CLI VARCHAR (10) NOT NULL,
CORREO_E_EMP VARCHAR (25) NOT NULL,
WEB VARCHAR(40)NOT NULL
)

CREATE TABLE CLIENTE_NATURAL(
COD_CLI VARCHAR (10) NOT NULL,
NOMBRES_CLI VARCHAR (20) NOT NULL,
APE_PATER_CLI VARCHAR (30) NOT NULL,
APE_MATER_CLI VARCHAR (30) NOT NULL,
)


CREATE TABLE DETALLE_BOLETA(
COD_BOL VARCHAR (10) NOT NULL,
COD_PRO VARCHAR (10) NOT NULL,
Cantidad INT NOT NULL,
PRECIOVENTA DECIMAL (8,2) NOT NULL
)


CREATE TABLE BOLETA(
COD_BOL VARCHAR (10) NOT NULL,
COD_EMP VARCHAR (10) NOT NULL,
FECHA_BOL DATETIME NOT NULL,
COD_CLI VARCHAR (10) NOT NULL,
ESTADO_BOL VARCHAR (10) NOT NULL
)

CREATE TABLE PRODUCTO(
COD_PRO VARCHAR (10) NOT NULL,
DESCRIP_PRO VARCHAR (40) NOT NULL,
PRECIO_PRO DECIMAL (8,2) NOT NULL,
STOCK_ACT_PRO INT NOT NULL,
STOCK_MIN_PRO INT NOT NULL,
COD_TIPO_PRO VARCHAR (10) NOT NULL
)


CREATE TABLE TIPO_PRODUCTO(
COD_TIPO_PROD VARCHAR (10) NOT NULL,
DESCRIP_TIPO_PROD VARCHAR (40) NOT NULL

)
